version: "3.2"
services:
  php:
    build: './php/'
    container_name: apache_php
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    volumes:
      - ./MySQL:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  apache:
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
networks:
  frontend:
  backend: