# Пропишем версию
version: '3.3'
# Перечислим сервисы
services:
    nginx:
        # Пропишем какой образ мы хотим использовать
        image: nginx:latest
        # Назовем свой контейнер по красивому
        container_name: nginx_1
        # Проброс портов
        ports:
            - "80:80"
            - "443:443"
        # Проброс папок
        volumes:
            - ./Nginx/core/:/etc/nginx/conf.d
            - ./Nginx/www/:/var/www/
            - ./Nginx/Logs/:/var/log/nginx/
        # Укажем зависимости
        links:
            - php

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        container_name: mysql_1
        # Пропишем настройки, предлагаю использовать вместо mypassword более сложный пароль, он пренадлежит root
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=mydatabase
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - ./MySQL:/var/lib/mysql

    php:
        # Билдим с помощью dockerfile указав директорию где он лежит
        build: ./PHP
        container_name: php-fpm-7.1
        volumes:
            - ./Nginx/www:/var/www
        links:
            - mysql:db
