# Пропишем версию
version: '3.3'
# Перечислим сервисы
services:
  nginx:
    image: nginx:latest
    container_name: production-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/conf.d/:/etc/nginx/conf.d/
      - ./Nginx/www/:/var/www
      - ./Nginx/logs/:/var/log/nginx/
      - /home/bood92/docker/docker_nginx_ssl/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /home/bood92/docker/docker_nginx_ssl/volume/etc/letsencrypt/live/host-5-58-202-113.bitternet.ua/fullchain.pem:/etc/letsencrypt/live/host-5-58-202-113.bitternet.ua/fullchain.pem
      - /home/bood92/docker/docker_nginx_ssl/volume/etc/letsencrypt/live/host-5-58-202-113.bitternet.ua/privkey.pem:/etc/letsencrypt/live/host-5-58-202-113.bitternet.ua/privkey.pem
    links:
      - php

  php:
    build: ./PHP
    container_name: php7.1-fpm
    volumes:
      - ./Nginx/www:/var/www
    links:
      - mysql:db
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql_5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./MySQL:/var/lib/mysql
